# thymeleaf
spring:
  thymeleaf:
    cache: false
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    servlet:
      content-type: text/html
    check-template-location: true
  #热部署
  #devtools:
    #restart:
      #enabled: true  #设置开启热部署
      #additional-paths: src/main/java #重启目录
      #exclude: static/**,templates/**
  freemarker:
    cache: false  #resource/**,static/**,templates/**下的资源更改后切换到浏览器就更新
  #数据源
  datasource:
    #url: jdbc:mysql://182.92.167.232:3306/aoxiang_db?serverTimezone=UTC
    url: jdbc:mysql://localhost:3306/zairui?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: Aoxiang2320
    type: com.alibaba.druid.pool.DruidDataSource
logging:
  level:
    root: WARN
    org.springframework.*: INFO
    sql: debug
